#yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json

services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located
