# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes: 
  auth:
    taskfile: "./auth-service/taskfile.yml"
    dir: "./auth-service"
    excludes: [default]
    
  app-rs:
    taskfile: "./app-service/taskfile.yml"
    dir: "./app-service"
    excludes: [default]
    
  sv:
    taskfile: "./app-sv/taskfile.yml"
    dir: "./app-sv"
    excludes: [default]

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  build:
    cmds:
      - docker compose build 

  up: 
    cmds:
      - docker compose -p rusty up -d 
      
  down: 
    cmds:
      - docker compose -p rusty down -v 
      
  start: 
    cmds:
      - docker compose -p rusty start
      
  stop: 
    cmds:
      - docker compose -p rusty stop
