//! Generated by shki - DO NOT EDIT

///User accounts
#[derive(Debug, Clone, sqlx::FromRow, serde::Deserialize, serde::Serialize)]
pub struct UserRow {
    pub email: String,
    pub password_hash: String,
    pub two_factor: String,
}

