# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  serve: 
    desc: Run the auth server
    cmds: 
      - cargo run


      
  watch:
    desc: Run auth server and re-compile on change
    cmds:
      - cargo watch -q -c -w src/ -w assets/ -x run

